### ISSUE TITLE
Support the --out / -o flag for the report output.

### ISSUE THREAD

**Issue by throup** [dutchiexl/BehatHtmlFormatterPlugin#2]
Behat has a flag `--out` or `-o` to specify where report output should be saved:

```
 --out (-o)            Write format output to a file/directory instead of
                       STDOUT (output_path). You can also provide different
                       outputs to multiple formats. (multiple values allowed)
```

It took me a little while to find the current output path (hard-coded to `{$PROJECTROOT}/vendor/emuse/behat-html-formatter/reports/test_report.html`). It is probably worth adding a note to the readme file to explain this until the extension can support user-defined paths.

**Comment by kwisatz** [comment]
Not supporting the `--out` flag as of yet, but made it possible to specify the output path as an argument in behat.yml in #3. I'll be looking at the flag now.

**Comment by dutchiexl** [comment]
Ok great, I will create a pull as soon as it is finished.

**Comment by dutchiexl** [comment]
Can you give an example of the usage of the output path in the readme file?

Thanks for the implementation!

**Comment by kwisatz** [comment]
Note that the implementation in #4 is still not respecting the `--out` flag. I haven't found a reference to its use in the Behat source files, so as of now I don't know how to override an output_path parameter passed to a formatter with a command line argument.

**Comment by dutchiexl** [comment]
The --out parameter seems to work ? Can I close this Issue ?

**Comment by dutchiexl** [comment]
Any suggestions on how to include the assets, if we make the path dynamic ?

**Comment by kwisatz** [comment]
@dutchiexl It does? I thought I had tested it and it seemed to get totally ignored…

As to the assets, indeed, I didn't think about those. But I guess the best solution would be to copy them to output_path/assets. This will also make the output work on CI servers that "publish" the report.

**Comment by dutchiexl** [comment]
For me it does, I think so to. I will implement it later :)

**Comment by throup** [comment]
Thanks for putting the effort in so promptly. It's almost there, but not quite... There seems to be an issue parsing the output path.

---

My project root is: `/home/throup/PhpstormProjects/Colourspace`

My `behat.yml` is:  `/home/throup/PhpstormProjects/Colourspace/config/behat.yml`

When I run the command from the project root:

```
vendor/bin/behat --config config/behat.yml --tags ~wip --format junit --out build/behat/ --format html --out docs/behat/
```

---

I expect to find:

junit report: `/home/throup/PhpstormProjects/Colourspace/build/behat/default.xml`

html report: `/home/throup/PhpstormProjects/Colourspace/docs/behat/test_report.html`.

---

I actually find:

junit report: `/home/throup/PhpstormProjects/Colourspace/build/behat/default.xml`

html report: `/home/throup/PhpstormProjects/Colourspace/config/home/throup/PhpstormProjects/Colourspace/docs/behat/test_report.html`

another html report: `/home/throup/PhpstormProjects/Colourspace/config/home/throup/PhpstormProjects/Colourspace/build/behat/test_report.html`

---

So it looks like two outstanding issues:
1. relative paths are not being processed correctly; they appear to be converted to an absolute path, but then this absolute path is treated as relative to the directory containing the `behat.yml` file (not necessarily the project root).
2. if two (or more, I would assume) format options are used, the html report grabs the output location for both/all of them.

**Comment by kwisatz** [comment]
Thanks for your feedback, @throup.

As I mentioned, the code is not tested with the --out parameter since I couldn't find any documentation, nor usage in the Behat source.
Have you tried specifying output_path in your behat.yml, is that working for you? Looks like the second html report at build/behat is from an output_path config setting.

From what you're describing, I suspect that `--out` is concatenating $PWD with the relative path specified, then passing this in as output_path. So maybe the value to output_path in behat.yml should actually be an absolute path and not a relative one and there should not be any concatenation done in FileOutputPrinter.

Looking at the paths argument to a suite configuration supports that assumption:

``` yml
    suites:
        web_features:
            paths:
                - %paths.base%/features/web
```

So maybe we should try to have

``` yml
    formatters:
        html:
            output_path: %paths.base%/build/html/behat
```

I'm sorry I don't have the time today to make these changes, but it should be simply a matter of not concatenating the path in FileOutputPrinter (and then being able to remove the addArgument('%paths.base%') call in the FormatterExtension implementation.

Alternatively, in FileOutputPrinter, use strpos to check if %paths.base% is already contained in the $path argument and then concatenate or not, depending on that check. (That would allow for both relative and absolute paths, but maybe that is too confusing to users.)

**Comment by throup** [comment]
Hi @kwisatz . I wasn't rushing you :-) ; was just going by @dutchiexl 's comment above suggesting `--out` was working.

The output above was based purely on using the `--out` flag; I have not specified an output_path in the `behat.yml` file because I don't want that report producing every time I run `behat`. Sometimes I run from the command line to see the pretty output; sometimes I use the Behat runner within PhpStorm; and sometimes I run from within a Phing build script to generate documents as part of a CI run in Jenkins. You can see the `behat.yml` file I was using: https://github.com/throup/colourspace/blob/master/config/behat.yml

When I _have_ specified the `output_path` setting, I have the same problem with the relative path being wrongly expanded within my `config` directory.

**Comment by dutchiexl** [comment]
I will fix this later today.

**Comment by dutchiexl** [comment]
I just removed the concatenation. The path in the config file should indeed be absolute :).
