### ISSUE TITLE
Generate report on each feature.

### ISSUE THREAD

**Issue by oabdelsamad2** [dutchiexl/BehatHtmlFormatterPlugin#86]
Hey all,
I was wondering if there's a way to generate the report on each feature? For example I have 10 features, and I need 10 reports not 1 report that contains all of them. Is that possible?

**Comment by DanTalash** [comment]
As far as I know this functionality is not present in this library. The only way I could see to do this would be:

* Trigger behat multiple times, specifying a different feature every time via `--name FEATURENAME`
* Providing a behat config with a different `output_path` or `file_name` for each feature. 
  * In order to do this you will either need to create a variety of `behat.yml` files by hand with different output folder/filenames.
  * Alternatively, create a script to take the base `behat.yml` and modify it for you on demand.

**Comment by donkidd** [comment]
@oabdelsamad2  have you had any success with this?  I'm looking to do the same thing and wondering if you've had any success?

**Comment by donkidd** [comment]
@oabdelsamad2 I ended up doing something similar to what @DanTalash recommended.  I have a "Multirun.pl" script that I use to actually run behat.  I have a few values that get substituted into my behat.yml.template file.  

So in my template file, I have this. 

```
emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
            name: html
            renderer: Twig,Behat2
            file_name: #FILE#
            print_args: true
            print_outp: true
            loop_break: true
```

And my Multirun.pl script will ultimately just do a substitution of the #FILE# parameter with a new file name I provide as a parameter.  Nothing too fancy but it gets my job done.  This also allows me to run behat multiple time and generate separate output for each run.

**Comment by PurHur** [comment]
This could easily done via the runner used. see above.
